services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: karabast-dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    environment:
      - DYNAMODB_LOCAL=true
    networks:
      - karabast-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
  s3-local:
    image: adobe/s3mock:latest
    container_name: karabast-s3-local
    ports:
      - "9090:9090"
    environment:
      - S3MOCK_INITIAL_BUCKETS=karabast-customization
    networks:
      - karabast-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9090/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  karabast-network:
    driver: bridge