import { parse, fold, render, validate } from '../../../swupgn/src/index';
import { checkKeyframes } from '../../../swupgn/src/integrity';
import * as fs from 'fs';
import * as path from 'path';

const dir = path.resolve(__dirname, '../../../../swupgn/test-vectors');

/**
 * The normative vectors (spec §20). Every `.swupgn` here must parse, validate without a single
 * issue, fold and render byte-for-byte to its `.fold.json` / `.render.txt`, carry a `%%% STORY`
 * equal to its own render, and pass the §14 keyframe gate clean -- so a reader that reproduces
 * these has implemented every rule the reference reader has, including the ones the gate
 * exercises (resources, credits, attachments, captures).
 *
 * The real-game vectors are regenerated by `SwuPgnVectors.spec.ts` with SWUPGN_WRITE_VECTORS=1;
 * `minimal` is hand-written and its STORY/fold/render derived from it.
 */
describe('canonical vectors', function () {
    const names = fs.readdirSync(dir).filter((f) => f.endsWith('.swupgn')).map((f) => f.replace('.swupgn', ''));
    for (const name of names) {
        const read = () => fs.readFileSync(path.join(dir, `${name}.swupgn`), 'utf8');

        it(`${name}: validates with no issue at all`, function () {
            expect(validate(read()).issues).toEqual([]);
        });
        it(`${name}: folds to the expected state`, function () {
            const expected = JSON.parse(fs.readFileSync(path.join(dir, `${name}.fold.json`), 'utf8'));
            const got = fold(parse(read()).events);
            expect(JSON.parse(JSON.stringify(got))).toEqual(expected);
        });
        // Rendered with NO injected resolver: the file's own %%% CARDS index supplies the
        // names, which is the point of the index — a .swupgn is self-describing.
        it(`${name}: renders to the expected story`, function () {
            const expected = fs.readFileSync(path.join(dir, `${name}.render.txt`), 'utf8').trim();
            expect(render(parse(read())).trim()).toBe(expected);
        });

        // The embedded %%% STORY must be exactly what the renderer produces, so the prose a
        // human reads can never drift from the events a machine folds.
        it(`${name}: embedded STORY matches the renderer`, function () {
            const doc = parse(read());
            expect((doc.story ?? []).join('\n').trim()).toBe(render(doc).trim());
        });

        // A vector with an internal contradiction would teach a reader the wrong rules: every
        // keyframe must be exactly what folding the deltas before it produces.
        it(`${name}: passes the keyframe gate clean`, function () {
            expect(checkKeyframes(parse(read()).events).mismatches).toEqual([]);
        });
    }
});
