import type { EventName } from '../Constants';
import type { AbilityContext } from '../ability/AbilityContext';
import type { Player } from '../Player';
import type { Card } from '../card/Card';
import type { ILastKnownInformation } from './LastKnownInformation';
import { GameEvent } from './GameEvent';

/**
 * Base class for strongly-typed game events. Each concrete subclass represents one
 * {@link EventName} and declares its payload properties explicitly, replacing the
 * dynamic property-bag pattern of the base {@link GameEvent}.
 *
 * Construction contract: subclass constructors take only `(context, cannotBeCancelled)`.
 * Payload properties are declared on the class but populated afterwards by the owning
 * {@link GameSystem}'s `addPropertiesToEvent` layering (and, for some properties, by
 * pre-resolution effects or event handlers at resolution time). The window during which
 * declared properties are unassigned is internal to `GameSystem.generateEvent` and is
 * never observable by game code.
 */
export abstract class TypedGameEvent extends GameEvent {
    protected constructor(name: EventName, context: AbilityContext, cannotBeCancelled = false) {
        super(name, context, { cannotBeCancelled });
    }
}

/**
 * Base class for typed events generated by a {@link GameSystem}.
 * Properties are assigned by {@link GameSystem.addPropertiesToEvent}.
 */
export abstract class PlayerTargetGameEvent extends TypedGameEvent {
    public player: Player;
    public contingentSourceEvent?: GameEvent;
}

/**
 * Base class for typed events generated by a {@link CardTargetSystem}.
 * The `card` property is assigned by {@link CardTargetSystem.addPropertiesToEvent};
 * `lastKnownInformation` is late-assigned via a pre-resolution effect when requested.
 *
 * @template TCard Narrows the type of `card` for events whose system restricts its legal
 * targets to a card subtype (via its target type filter / canAffect checks). The narrowing
 * is not checked at assignment time, so the owning system should enforce it with a contract
 * assertion in `addPropertiesToEvent`.
 */
export abstract class CardTargetGameEvent<TCard extends Card = Card> extends PlayerTargetGameEvent {
    public card: TCard;
    public lastKnownInformation?: ILastKnownInformation;
}
