const mockCards = [
    buildMockCard({
        title: 'Doctor Aphra',
        subtitle: 'Digging For Answers',
        power: 4,
        hp: 5,
        cost: 4,
        hasNonKeywordAbility: true,
        aspects: ['Aggression'],
        types: ['unit'],
        traits: ['underworld'],
        setId: {
            set: 'LAW',
            number: 194,
        },
        unique: true,
        arena: 'ground',
        internalName: 'doctor-aphra#digging-for-answers',
    }),
    buildMockCard({
        title: 'Asajj Ventress',
        subtitle: 'Reluctant Hunter',
        power: 3,
        hp: 3,
        cost: 5,
        hasNonKeywordAbility: true,
        aspects: ['Command', 'Aggression'],
        types: ['unit'],
        traits: ['force', 'underworld', 'bounty hunter'],
        setId: {
            set: 'LAW',
            number: 61,
        },
        unique: true,
        arena: 'ground',
        internalName: 'asajj-ventress#reluctant-hunter',
    }),
    buildMockCard({
        title: 'Honor-Bound Partisan',
        power: 2,
        hp: 2,
        cost: 2,
        hasNonKeywordAbility: true,
        aspects: ['Command', 'Aggression'],
        types: ['unit'],
        traits: ['rebel', 'twi\'lek'],
        setId: {
            set: 'LAW',
            number: 58,
        },
        unique: false,
        arena: 'ground',
        internalName: 'honorbound-partisan',
    }),
    buildMockCard({
        title: 'Highsinger',
        subtitle: 'Deadly Droid',
        power: 4,
        hp: 2,
        cost: 3,
        hasNonKeywordAbility: true,
        aspects: ['Command', 'Aggression'],
        types: ['unit'],
        traits: ['underworld', 'droid', 'bounty hunter'],
        setId: {
            set: 'LAW',
            number: 59,
        },
        unique: true,
        arena: 'ground',
        internalName: 'highsinger#deadly-droid',
    }),
    buildMockCard({
        title: 'Defiant Hammerhead',
        power: 6,
        hp: 6,
        cost: 6,
        hasNonKeywordAbility: true,
        aspects: ['Command', 'Aggression'],
        types: ['unit'],
        traits: ['rebel', 'vehicle', 'capital ship'],
        setId: {
            set: 'LAW',
            number: 62,
        },
        unique: false,
        arena: 'space',
        internalName: 'defiant-hammerhead',
    }),
    buildMockCard({
        title: 'IG-88',
        subtitle: 'Programmed to Kill',
        power: 6,
        hp: 3,
        cost: 4,
        keywords: ['shielded'],
        hasNonKeywordAbility: false,
        aspects: ['Vigilance', 'Aggression', 'Villainy'],
        types: ['unit'],
        traits: ['underworld', 'droid', 'bounty hunter'],
        setId: {
            set: 'LAW',
            number: 42,
        },
        unique: true,
        arena: 'ground',
        internalName: 'ig88#programmed-to-kill',
    }),
    buildMockCard({
        title: 'Liberated Wookiee',
        power: 2,
        hp: 4,
        cost: 2,
        hasNonKeywordAbility: false,
        aspects: ['Command', 'Heroism'],
        types: ['unit'],
        traits: ['wookiee'],
        setId: {
            set: 'LAW',
            number: 143,
        },
        unique: false,
        arena: 'ground',
        internalName: 'liberated-wookiee',
    }),
    buildMockCard({
        title: 'Lost and Forgotten',
        cost: 6,
        hasNonKeywordAbility: true,
        aspects: ['Vigilance'],
        types: ['event'],
        traits: ['innate'],
        setId: {
            set: 'LAW',
            number: 133,
        },
        unique: false,
        internalName: 'lost-and-forgotten',
    }),
    buildMockCard({
        title: 'Arvel Skeen',
        subtitle: 'Win and Walk Away',
        power: 4,
        hp: 3,
        cost: 3,
        hasNonKeywordAbility: true,
        aspects: ['Aggression'],
        types: ['unit'],
        traits: ['rebel'],
        setId: {
            set: 'LAW',
            number: 191,
        },
        unique: true,
        arena: 'ground',
        internalName: 'arvel-skeen#win-and-walk-away',
    }),
    buildMockCard({
        title: 'Cad Bane',
        subtitle: 'Now It\'s My Turn',
        power: 6,
        hp: 6,
        cost: 6,
        keywords: ['shielded', 'overwhelm'],
        hasNonKeywordAbility: true,
        aspects: ['Vigilance', 'Command', 'Villainy'],
        types: ['unit'],
        traits: ['underworld', 'bounty hunter'],
        setId: {
            set: 'LAW',
            number: 32,
        },
        unique: true,
        arena: 'ground',
        internalName: 'cad-bane#now-its-my-turn',
    }),
    buildMockCard({
        title: 'Aurra Sing',
        subtitle: 'Assassin',
        power: 3,
        hp: 7,
        cost: 7,
        hasNonKeywordAbility: true,
        aspects: ['Vigilance', 'Villainy'],
        types: ['leader'],
        traits: ['underworld', 'bounty hunter'],
        setId: {
            set: 'LAW',
            number: 4,
        },
        unique: true,
        arena: 'ground',
        internalName: 'aurra-sing#assassin',
    }),
    buildMockCard({
        title: 'Adventurer Sniper Rifle',
        power: 0,
        hp: 0,
        upgradeHp: 0,
        upgradePower: 0,
        cost: 2,
        hasNonKeywordAbility: true,
        aspects: ['Vigilance'],
        types: ['upgrade'],
        traits: ['item', 'weapon'],
        setId: {
            set: 'LAW',
            number: 126,
        },
        unique: false,
        internalName: 'adventurer-sniper-rifle',
    }),
    buildMockCard({
        title: 'Governor\'s Shuttle',
        power: 2,
        hp: 4,
        cost: 5,
        hasNonKeywordAbility: true,
        aspects: ['Vigilance', 'Villainy'],
        types: ['unit'],
        traits: ['imperial', 'vehicle', 'transport'],
        setId: {
            set: 'LAW',
            number: 99,
        },
        unique: false,
        arena: 'space',
        internalName: 'governors-shuttle',
    }),
    buildMockCard({
        title: 'Mastery',
        power: 3,
        hp: 3,
        upgradeHp: 3,
        upgradePower: 3,
        cost: 4,
        hasNonKeywordAbility: true,
        aspects: ['Vigilance'],
        types: ['upgrade'],
        traits: ['learned'],
        setId: {
            set: 'LAW',
            number: 129,
        },
        unique: false,
        internalName: 'mastery',
    }),
    buildMockCard({
        title: 'Hold For Questioning',
        cost: 3,
        hasNonKeywordAbility: true,
        aspects: ['Cunning', 'Villainy'],
        types: ['event'],
        traits: ['law'],
        setId: {
            set: 'LAW',
            number: 217,
        },
        unique: false,
        internalName: 'hold-for-questioning',
    }),
    buildMockCard({
        title: 'Display Piece',
        cost: 4,
        hasNonKeywordAbility: true,
        aspects: ['Vigilance', 'Villainy'],
        types: ['event'],
        traits: ['supply'],
        setId: {
            set: 'LAW',
            number: 103,
        },
        unique: false,
        internalName: 'display-piece',
    }),
    buildMockCard({
        title: 'The Stranger',
        subtitle: 'No Survivors',
        power: 1,
        hp: 7,
        cost: 5,
        keywords: ['ambush', 'grit'],
        hasNonKeywordAbility: true,
        aspects: ['Vigilance', 'Cunning', 'Villainy'],
        types: ['unit'],
        traits: ['force', 'sith'],
        setId: {
            set: 'LAW',
            number: 86,
        },
        unique: true,
        arena: 'ground',
        internalName: 'the-stranger#no-survivors',
    }),
    buildMockCard({
        title: 'Windfall',
        cost: 5,
        hasNonKeywordAbility: true,
        aspects: ['Cunning'],
        types: ['event'],
        traits: ['supply'],
        setId: {
            set: 'LAW',
            number: 248,
        },
        unique: false,
        internalName: 'windfall',
    }),
    buildMockCard({
        title: 'Hunter for Hire',
        power: 4,
        hp: 4,
        cost: 3,
        hasNonKeywordAbility: true,
        aspects: ['Command'],
        types: ['unit'],
        traits: ['underworld', 'bounty hunter'],
        setId: {
            set: 'LAW',
            number: 156,
        },
        unique: false,
        arena: 'ground',
        internalName: 'hunter-for-hire',
    }),
    buildMockCard({
        title: 'Storm Raider',
        power: 2,
        hp: 2,
        cost: 1,
        hasNonKeywordAbility: false,
        aspects: ['aggression', 'villainy'],
        types: ['unit'],
        keywords: ['raid 1'],
        traits: ['underworld', 'nihil'],
        setId: {
            set: 'LAW',
            number: 172,
        },
        unique: false,
        arena: 'ground',
        internalName: 'storm-raider',
    }),
    buildMockCard({
        title: 'Targeted For Removal',
        power: 0,
        hp: 0,
        upgradePower: 0,
        upgradeHp: 0,
        cost: 3,
        hasNonKeywordAbility: true,
        aspects: ['command', 'villainy'],
        types: ['upgrade'],
        traits: ['condition'],
        setId: {
            set: 'LAW',
            number: 141,
        },
        unique: false,
        internalName: 'targeted-for-removal',
    }),
    buildMockCard({
        title: 'Liberty',
        subtitle: 'Draw Their Fire!',
        power: 9,
        hp: 7,
        cost: 8,
        hasNonKeywordAbility: true,
        keywords: ['sentinel'],
        aspects: ['Cunning', 'Heroism'],
        types: ['unit'],
        traits: ['rebel', 'vehicle', 'capital ship'],
        setId: {
            set: 'LAW',
            number: 224,
        },
        unique: true,
        arena: 'space',
        internalName: 'liberty#draw-their-fire',
    }),
    buildMockCard({
        title: 'K-2SO',
        subtitle: 'Locking the Vault',
        power: 3,
        hp: 5,
        cost: 5,
        hasNonKeywordAbility: true,
        keywords: ['ambush'],
        aspects: ['Aggression', 'Cunning', 'Heroism'],
        types: ['unit'],
        traits: ['rebel', 'droid'],
        setId: {
            set: 'LAW',
            number: 79,
        },
        unique: true,
        arena: 'ground',
        internalName: 'k2so#locking-the-vault',
    }),
    buildMockCard({
        title: 'Zuckuss',
        subtitle: 'Dangerous',
        power: 3,
        hp: 5,
        cost: 4,
        hasNonKeywordAbility: true,
        keywords: ['saboteur'],
        aspects: ['Command', 'Cunning', 'Villainy'],
        types: ['unit'],
        traits: ['underworld', 'bounty hunter'],
        setId: {
            set: 'LAW',
            number: 64,
        },
        unique: true,
        arena: 'ground',
        internalName: 'zuckuss#dangerous',
    }),
    buildMockCard({
        title: 'Bossk',
        subtitle: 'Join Our Merry Band',
        power: 3,
        hp: 5,
        cost: 4,
        hasNonKeywordAbility: true,
        aspects: ['Vigilance', 'Command', 'Villainy'],
        types: ['unit'],
        traits: ['underworld', 'bounty hunter'],
        setId: {
            set: 'LAW',
            number: 31,
        },
        unique: true,
        arena: 'ground',
        internalName: 'bossk#join-our-merry-band',
    }),
    buildMockCard({
        title: 'Undercity Hunting Team',
        power: 5,
        hp: 5,
        cost: 5,
        hasNonKeywordAbility: true,
        aspects: ['Command', 'Villainy'],
        types: ['unit'],
        traits: ['underworld', 'bounty hunter'],
        setId: {
            set: 'LAW',
            number: 138,
        },
        unique: false,
        arena: 'ground',
        internalName: 'undercity-hunting-team',
    }),
    buildMockCard({
        title: 'Canto Bight Security',
        power: 3,
        hp: 5,
        cost: 5,
        hasNonKeywordAbility: true,
        aspects: ['Vigilance'],
        keywords: ['sentinel'],
        types: ['unit'],
        traits: ['fringe'],
        setId: {
            set: 'LAW',
            number: 121,
        },
        unique: false,
        arena: 'ground',
        internalName: 'canto-bight-security',
    }),
    buildMockCard({
        title: 'Imperial Door Technician',
        power: 2,
        hp: 2,
        cost: 1,
        hasNonKeywordAbility: true,
        aspects: ['Vigilance', 'Villainy'],
        types: ['unit'],
        traits: ['imperial', 'trooper'],
        setId: {
            set: 'LAW',
            number: 97,
        },
        unique: false,
        arena: 'ground',
        internalName: 'imperial-door-technician',
    }),
    buildMockCard({
        title: 'Choke on Aspirations',
        cost: 1,
        hasNonKeywordAbility: true,
        aspects: ['Vigilance', 'Villainy'],
        types: ['event'],
        traits: ['force'],
        setId: {
            set: 'LAW',
            number: 102,
        },
        unique: false,
        internalName: 'choke-on-aspirations',
    }),
    buildMockCard({
        title: 'Tear This Ship Apart',
        cost: 7,
        hasNonKeywordAbility: true,
        aspects: ['Command', 'Cunning', 'Villainy'],
        types: ['event'],
        traits: ['tactic'],
        setId: {
            set: 'LAW',
            number: 66,
        },
        unique: false,
        internalName: 'tear-this-ship-apart',
    }),
    buildMockCard({
        title: 'Hound\'s Tooth',
        subtitle: 'Hunter\'s Approach',
        power: 4,
        hp: 8,
        cost: 7,
        hasNonKeywordAbility: true,
        aspects: ['Vigilance', 'Command', 'Villainy'],
        types: ['unit'],
        traits: ['underworld', 'vehicle', 'transport'],
        setId: {
            set: 'LAW',
            number: 33,
        },
        unique: true,
        arena: 'space',
        internalName: 'hounds-tooth#hunters-approach',
    }),
    buildMockCard({
        title: 'Boba Fett',
        subtitle: 'Krayt\'s Claw Commander',
        power: 3,
        hp: 6,
        cost: 5,
        hasNonKeywordAbility: true,
        aspects: ['command', 'villainy'],
        types: ['leader'],
        keywords: ['raid 1'],
        traits: ['underworld', 'bounty hunter'],
        setId: {
            set: 'LAW',
            number: 7,
        },
        unique: true,
        arena: 'ground',
        internalName: 'boba-fett#krayts-claw-commander',
    }),
    buildMockCard({
        title: 'Chewbacca',
        subtitle: 'Hero of Kessel',
        power: 5,
        hp: 6,
        cost: 4,
        hasNonKeywordAbility: true,
        aspects: ['aggression', 'heroism'],
        types: ['leader'],
        traits: ['underworld', 'wookiee'],
        setId: {
            set: 'LAW',
            number: 13,
        },
        unique: true,
        arena: 'ground',
        internalName: 'chewbacca#hero-of-kessel',
    }),
    buildMockCard({
        title: 'Broken Horn',
        subtitle: 'Vizago\'s Pride',
        power: 5,
        hp: 4,
        cost: 5,
        hasNonKeywordAbility: true,
        aspects: ['Aggression', 'Cunning'],
        types: ['unit'],
        traits: ['underworld', 'vehicle', 'transport'],
        setId: {
            set: 'LAW',
            number: 83,
        },
        unique: true,
        arena: 'space',
        internalName: 'broken-horn#vizagos-pride',
    }),
    buildMockCard({
        title: 'Krrsantan',
        subtitle: 'Hit and Run',
        power: 7,
        hp: 7,
        cost: 8,
        hasNonKeywordAbility: true,
        aspects: ['Aggression', 'Cunning'],
        keywords: ['ambush', 'overwhelm'],
        types: ['unit'],
        traits: ['underworld', 'wookiee', 'bounty hunter'],
        setId: {
            set: 'LAW',
            number: 84,
        },
        unique: true,
        arena: 'ground',
        internalName: 'krrsantan#hit-and-run',
    }),
    buildMockCard({
        title: 'Every Day, More Lies',
        cost: 1,
        hasNonKeywordAbility: true,
        aspects: ['Aggression'],
        types: ['event'],
        traits: ['innate'],
        setId: {
            set: 'LAW',
            number: 204,
        },
        unique: false,
        internalName: 'every-day-more-lies',
    }),
    buildMockCard({
        title: 'Droid Laser Turret',
        power: 2,
        hp: 1,
        cost: 3,
        hasNonKeywordAbility: false,
        aspects: ['Vigilance'],
        keywords: ['sentinel', 'shielded'],
        types: ['unit'],
        traits: ['droid'],
        setId: {
            set: 'LAW',
            number: 118,
        },
        unique: false,
        arena: 'ground',
        internalName: 'droid-laser-turret',
    }),
    buildMockCard({
        title: 'Bith Brute',
        power: 4,
        hp: 3,
        cost: 3,
        hasNonKeywordAbility: false,
        aspects: ['Vigilance', 'Aggression'],
        keywords: ['sentinel', 'saboteur'],
        types: ['unit'],
        traits: ['underworld'],
        setId: {
            set: 'LAW',
            number: 49,
        },
        unique: false,
        arena: 'ground',
        internalName: 'bith-brute',
    }),
    buildMockCard({
        title: 'Honnah',
        subtitle: 'Oink! Squee!',
        power: 3,
        hp: 5,
        cost: 4,
        hasNonKeywordAbility: false,
        aspects: ['Vigilance', 'Aggression'],
        keywords: ['raid 2', 'restore 2'],
        types: ['unit'],
        traits: ['underworld', 'bounty hunter'],
        setId: {
            set: 'LAW',
            number: 50,
        },
        unique: true,
        arena: 'ground',
        internalName: 'honnah#oink-squee',
    }),
    buildMockCard({
        title: 'Maz Kanata',
        subtitle: 'Where\'s My Boyfriend?',
        power: 4,
        hp: 4,
        cost: 5,
        hasNonKeywordAbility: true,
        aspects: ['Command', 'Cunning'],
        types: ['unit'],
        traits: ['underworld'],
        setId: {
            set: 'LAW',
            number: 74,
        },
        unique: true,
        arena: 'ground',
        internalName: 'maz-kanata#wheres-my-boyfriend',
    }),
];

/** @param {{ title: string, subtitle: string?, hasNonKeywordAbility: boolean, cost: number?, hp: number?, arena?: string, unique: boolean, upgradeHp: number?, upgradePower: number?, aspects: string[]?, traits: string[]?, keywords: string[]?, types: string[], setId: { set: string, number: number }, internalName: string }} cardData */
function buildMockCard(cardData) {
    let textElements = [];
    let keywords = [];
    if (cardData.keywords) {
        const capitalizedKeywords = cardData.keywords?.map((keyword) => keyword.charAt(0).toUpperCase() + keyword.slice(1));
        textElements.push(...capitalizedKeywords);

        // grab the first token for cases like "restore 1"
        keywords.push(...cardData.keywords.map((keyword) => keyword.split(' ')[0]));
    }
    if (cardData.hasNonKeywordAbility) {
        textElements.push('mock ability text');
    }

    const abilityText = textElements.join('\n');
    let deployBox = null;
    let text = '';
    if (cardData.types.includes('leader')) {
        deployBox = abilityText;
    } else {
        text = abilityText;
    }

    return {
        title: cardData.title,
        subtitle: cardData.subtitle || '',
        cost: cardData.cost ?? null,
        hp: cardData.hp ?? null,
        power: cardData.power ?? null,
        text,
        deployBox,
        epicAction: '',
        unique: cardData.unique,
        rules: null,
        upgradePower: cardData.upgradePower ?? null,
        upgradeHp: cardData.upgradeHp ?? null,
        id: cardData.internalName + '-id',
        aspects: cardData.aspects || [],
        traits: cardData.traits || [],
        keywords,
        types: cardData.types,
        setId: cardData.setId,
        setCodes: [cardData.setId],
        internalName: cardData.internalName,
        arena: cardData.arena || null,
    };
}

function buildSetStr(card) {
    return `${card.setId.set}_${card.setId.number}`;
}

function addMockCards(cards) {
    const mockCardsById = new Map();
    const mockCardNames = [];

    const allCards = [];

    for (const card of mockCards) {
        mockCardsById.set(buildSetStr(card), card);
        mockCardNames.push(card.internalName);
        allCards.push(card);
    }

    for (const card of cards) {
        const setStr = buildSetStr(card);
        if (mockCardsById.has(setStr)) {
            // uncomment the below to emit a log line for each mock card that is now in the official data
            // console.log(color(`\nCard '${setStr}' found in official data. The mock can now be safely removed from mockdata.js`, 'yellow'));

            continue;
        }

        allCards.push(card);
    }

    return { mockCardNames, cards: allCards };
}

module.exports = { addMockCards };
