// Generated by ts-to-zod
import { z } from 'zod';
import type { IDeckDataEntity } from './DynamoDBInterfaces';

export const iUserDataEntitySchema = z.object({
    id: z.string(),
    username: z.string(),
    preferences: z.record(z.any()).optional(),
});

export const iMatchupStatEntitySchema = z.object({
    leaderId: z.string(),
    baseId: z.string(),
    wins: z.number(),
    losses: z.number(),
    draws: z.number(),
});

export const iDeckStatsEntitySchema = z.object({
    wins: z.number(),
    losses: z.number(),
    draws: z.number(),
    statsByMatchup: z.array(iMatchupStatEntitySchema).optional(),
});
export const iDeckDataEntitySchema = z.object({
    id: z.string(),
    userId: z.string(),
    deck: z.object({
        leader: z.object({
            id: z.string(),
        }),
        base: z.object({
            id: z.string(),
        }),
        name: z.string(),
        favourite: z.boolean(),
        deckLink: z.string(),
        deckLinkID: z.string(),
        source: z.string().optional(),
    }),
    stats: iDeckStatsEntitySchema.optional(),
}) as z.ZodType<IDeckDataEntity>;

