// Generated by ts-to-zod
import { z } from 'zod';
import { type IDeckDataEntity, ModActionType } from './DynamoDBInterfaces';

export const IUserDataEntitySchema = z.object({
    id: z.string(),
    username: z.string(),
    preferences: z.record(z.any()).optional(),
});

export const IMatchupStatEntitySchema = z.object({
    leaderId: z.string(),
    baseId: z.string(),
    wins: z.number(),
    losses: z.number(),
    draws: z.number(),
});

export const IDeckStatsEntitySchema = z.object({
    wins: z.number(),
    losses: z.number(),
    draws: z.number(),
    statsByMatchup: z.array(IMatchupStatEntitySchema).optional(),
});
export const IDeckDataEntitySchema = z.object({
    id: z.string(),
    userId: z.string(),
    deck: z.object({
        leader: z.object({
            id: z.string(),
        }),
        base: z.object({
            id: z.string(),
        }),
        name: z.string(),
        favourite: z.boolean(),
        deckLink: z.string(),
        deckLinkID: z.string(),
        source: z.string().optional(),
    }),
    stats: IDeckStatsEntitySchema.optional(),
}) as z.ZodType<IDeckDataEntity>;

// generated by chat-gpt
export const ServerRoleUsersListsSchema = z.object({
    admins: z.array(z.string().uuid()),
    developers: z.array(z.string().uuid()),
    moderators: z.array(z.string().uuid()),
});

export const ModActionSubmitSchema = z.object({
    playerId: z.string().min(1, 'playerId is required'),
    actionType: z.nativeEnum(ModActionType),
    durationDays: z.number().positive()
        .nullable()
        .optional(),
    note: z.string(),
}).refine(
    (data) => {
        // If actionType is Mute, durationDays must be a positive number
        if (data.actionType === ModActionType.Mute) {
            return typeof data.durationDays === 'number' && data.durationDays > 0;
        }
        return true;
    },
    { message: 'durationDays is required and must be positive for Mute actions', path: ['durationDays'] }
);

export const ModActionCancelSchema = z.object({
    modActionId: z.string().min(1, 'modActionId is required'),
    playerId: z.string().min(1, 'playerId is required'),
});

export const FindUserSchema = z.object({
    searchQuery: z.string().min(1, 'searchQuery is required'),
});

